### ISSUE TITLE
.

### ISSUE THREAD

**Issue by paragonie-scott** [gilfether/phpcrypt#6]

**Comment by paragonie-scott** [comment]
![cytme9tvaaeyylj](https://cloud.githubusercontent.com/assets/11591518/12371045/6364e0ec-bbf4-11e5-9da1-f3af368dc5e9.png)

**Comment by paragonie-scott** [comment]
Also it appears that every cipher (from your long list, which includes such gems as `SimpleXor` and `Vigenere` for some reason!) is vulnerable to chosen-ciphertext attacks, since you aren't authenticating your ciphertext in an Encrypt then MAC mode.

**Comment by geggleto** [comment]
@paragonie-scott the Robinhood of PHP Security :)

**Comment by larthoman** [comment]
On behalf of the PHP community I would like to apologize for paragonie-scott's tactics and conduct. Reading up on the matter at https://www.reddit.com/r/PHP/comments/41dnct/full_disclosure_it_essentially_wins_crypto/ it is my belief this library isn't anywhere near as bad as paragonie-scott has implied. Sure, there's room for improvement, but the kind of vitriol that paragonie-scott has attempted to throw your away is totally uncalled for.

**Comment by damm** [comment]
one problem is when people write cryptography (libraries/ extensions) when they have no knowledge of expertise in said matter.  The other problem is having your cryptography code reviewed (externally or internally) every now and then.  

the NSA and CIA has been trying to subvert cryptography since the early 90's.  We are starting to see the fallouts from this.  (If you google Dual EC NSA you'll see good stories).  With Certain large projects having issues with their own QA (that most of the world depends on for SSL / TLS ) it's become more important to ensure our crypto works as intended.  

Unfortunately that is the point; we don't live in an ideal world where your secrets are safe.  Government and other entities would love to hack you and steal your data.  Someday we will live in a world where any 18 year old can learn cryptography and drop it on github and it won't matter if it's insecure.

That's just not today.

P.S. I don't know the age of the author; I was just making a point that most 18 year olds think they know what is right (and they are right).  So it makes it easier for them to do things they don't have a firm grasp on.

Wish I was 18 somedays.

**Comment by paragonie-scott** [comment]
@larthoman If you think your way is better, fine. Everyone listen to the expert.

I'll leave you with this: https://cr.yp.to/talks/2015.01.07/slides-djb-20150107-a4.pdf

I'm done.

**Comment by joepie91** [comment]
@larthoman You do not and cannot speak for "the PHP community".

And I can't believe that I still have to say this: **Your ego does not come before the security and safety of others.** No, it is **not** acceptable to publish a broken cryptography library like this without a string of "don't actually use this" warnings right at the very top. It is _extremely_ irresponsible to do otherwise.

**Comment by ahmetb** [comment]
@larthoman 

> /opens anonymous account just to reply here
> /claims "on behalf of the PHP community"

top shelf lol m8.

![image](https://cloud.githubusercontent.com/assets/159209/12403753/f97bde30-bdea-11e5-9435-055b30d0b4fa.png)
